// <auto-generated />
using System;
using ChoicePie.Backend.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChoicePie.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChoicePieDbContext))]
    [Migration("20260724011541_AddQuizReport")]
    partial class AddQuizReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.AdminAuthAccount.AdminAuthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.HasKey("Id")
                        .HasName("pk_admin_auth_account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_auth_account_email");

                    b.ToTable("admin_auth_account", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.AdminUser.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_admin_user");

                    b.ToTable("admin_user", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.AuthAccount.AuthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_account_email");

                    b.ToTable("auth_account", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.Comment.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_comment_quiz_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.CreatorFollow.CreatorFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<Guid>("FollowedCreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("followed_creator_id");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.HasKey("Id")
                        .HasName("pk_creator_follow");

                    b.HasIndex("CreatorId", "FollowedCreatorId")
                        .IsUnique()
                        .HasDatabaseName("ix_creator_follow_creator_id_followed_creator_id");

                    b.ToTable("creator_follow", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.GameSession.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverEmoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_emoji");

                    b.Property<string>("CoverGradient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_gradient");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_user_id");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime>("PlayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at_utc");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<string>("QuizTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quiz_title");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("room_code");

                    b.HasKey("Id")
                        .HasName("pk_game_session");

                    b.HasIndex("HostUserId")
                        .HasDatabaseName("ix_game_session_host_user_id");

                    b.HasIndex("RoomCode")
                        .HasDatabaseName("ix_game_session_room_code");

                    b.ToTable("game_session", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.Member.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspended");

                    b.Property<DateTime?>("LastAiGenerationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ai_generation_at");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<string>("SuspendedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspended_reason");

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_until");

                    b.HasKey("Id")
                        .HasName("pk_member");

                    b.ToTable("member", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.Quiz.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<int>("ShareCount")
                        .HasColumnType("integer")
                        .HasColumnName("share_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("TakedownAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("takedown_at");

                    b.Property<Guid?>("TakedownBy")
                        .HasColumnType("uuid")
                        .HasColumnName("takedown_by");

                    b.Property<string>("TakedownReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("takedown_reason");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_quiz");

                    b.ToTable("quiz", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.QuizAttempt.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.PrimitiveCollection<Guid[]>("ExpectedQuestionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("expected_question_ids");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_quiz_attempt");

                    b.HasIndex("QuizId", "MemberId")
                        .HasDatabaseName("ix_quiz_attempt_quiz_id_member_id");

                    b.ToTable("quiz_attempt", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.QuizFavorite.QuizFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.HasKey("Id")
                        .HasName("pk_quiz_favorite");

                    b.HasIndex("CreatorId", "QuizId")
                        .IsUnique()
                        .HasDatabaseName("ix_quiz_favorite_creator_id_quiz_id");

                    b.ToTable("quiz_favorite", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.QuizReport.QuizReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_quiz_report");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_quiz_report_quiz_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_quiz_report_status");

                    b.ToTable("quiz_report", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.RefreshToken.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("LastModiferId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifer_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("OwnerId", "OwnerType")
                        .HasDatabaseName("ix_refresh_token_owner_id_owner_type");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.AdminAuthAccount.AdminAuthAccount", b =>
                {
                    b.OwnsMany("ChoicePie.Backend.Domain.Aggregates.AdminAuthAccount.Entities.AdminLoginMethod", "LoginMethods", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AdminAuthAccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("admin_auth_account_id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid?>("CreatorId")
                                .HasColumnType("uuid")
                                .HasColumnName("creator_id");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<Guid?>("DeleterId")
                                .HasColumnType("uuid")
                                .HasColumnName("deleter_id");

                            b1.Property<Guid?>("LastModiferId")
                                .HasColumnType("uuid")
                                .HasColumnName("last_modifer_id");

                            b1.Property<DateTime>("LastModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.HasKey("Id");

                            b1.HasIndex("AdminAuthAccountId")
                                .HasDatabaseName("ix_admin_login_method_admin_auth_account_id");

                            b1.ToTable("admin_login_method", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AdminAuthAccountId")
                                .HasConstraintName("fk_admin_login_method_admin_auth_account_admin_auth_account_id");

                            b1.OwnsOne("ChoicePie.Backend.Shared.Kernel.ValueObjects.HashedPassword", "Password", b2 =>
                                {
                                    b2.Property<Guid>("AdminLoginMethodId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Hash")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("PasswordHash");

                                    b2.Property<string>("Salt")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Salt");

                                    b2.HasKey("AdminLoginMethodId");

                                    b2.ToTable("admin_login_method");

                                    b2.WithOwner()
                                        .HasForeignKey("AdminLoginMethodId")
                                        .HasConstraintName("fk_admin_login_method_admin_login_method_id");
                                });

                            b1.OwnsOne("ChoicePie.Backend.Domain.Aggregates.AdminAuthAccount.ValueObjects.AdminExternalIdentity", "External", b2 =>
                                {
                                    b2.Property<Guid>("AdminLoginMethodId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("Provider")
                                        .HasColumnType("integer")
                                        .HasColumnName("Provider");

                                    b2.Property<string>("ProviderUserId")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("ProviderUserId");

                                    b2.HasKey("AdminLoginMethodId");

                                    b2.ToTable("admin_login_method");

                                    b2.WithOwner()
                                        .HasForeignKey("AdminLoginMethodId")
                                        .HasConstraintName("fk_admin_login_method_admin_login_method_id");
                                });

                            b1.Navigation("External");

                            b1.Navigation("Password");
                        });

                    b.Navigation("LoginMethods");
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.AuthAccount.AuthAccount", b =>
                {
                    b.OwnsMany("ChoicePie.Backend.Domain.Aggregates.AuthAccount.Entities.LoginMethod", "LoginMethods", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AuthAccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("auth_account_id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid?>("CreatorId")
                                .HasColumnType("uuid")
                                .HasColumnName("creator_id");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<Guid?>("DeleterId")
                                .HasColumnType("uuid")
                                .HasColumnName("deleter_id");

                            b1.Property<Guid?>("LastModiferId")
                                .HasColumnType("uuid")
                                .HasColumnName("last_modifer_id");

                            b1.Property<DateTime>("LastModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.HasKey("Id");

                            b1.HasIndex("AuthAccountId")
                                .HasDatabaseName("ix_login_method_auth_account_id");

                            b1.ToTable("login_method", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AuthAccountId")
                                .HasConstraintName("fk_login_method_auth_account_auth_account_id");

                            b1.OwnsOne("ChoicePie.Backend.Shared.Kernel.ValueObjects.HashedPassword", "Password", b2 =>
                                {
                                    b2.Property<Guid>("LoginMethodId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Hash")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("PasswordHash");

                                    b2.Property<string>("Salt")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Salt");

                                    b2.HasKey("LoginMethodId");

                                    b2.ToTable("login_method");

                                    b2.WithOwner()
                                        .HasForeignKey("LoginMethodId")
                                        .HasConstraintName("fk_login_method_login_method_id");
                                });

                            b1.OwnsOne("ChoicePie.Backend.Domain.Aggregates.AuthAccount.ValueObjects.ExternalIdentity", "External", b2 =>
                                {
                                    b2.Property<Guid>("LoginMethodId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("Provider")
                                        .HasColumnType("integer")
                                        .HasColumnName("Provider");

                                    b2.Property<string>("ProviderUserId")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("ProviderUserId");

                                    b2.HasKey("LoginMethodId");

                                    b2.ToTable("login_method");

                                    b2.WithOwner()
                                        .HasForeignKey("LoginMethodId")
                                        .HasConstraintName("fk_login_method_login_method_id");
                                });

                            b1.Navigation("External");

                            b1.Navigation("Password");
                        });

                    b.Navigation("LoginMethods");
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.GameSession.GameSession", b =>
                {
                    b.OwnsMany("ChoicePie.Backend.Domain.Aggregates.GameSession.ValueObjects.GameSessionPlayerResult", "PlayerResults", b1 =>
                        {
                            b1.Property<Guid>("GameSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("game_session_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Answers")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("answers");

                            b1.Property<int>("FinalScore")
                                .HasColumnType("integer")
                                .HasColumnName("final_score");

                            b1.Property<Guid?>("MemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("member_id");

                            b1.Property<string>("Nickname")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("nickname");

                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid")
                                .HasColumnName("player_id");

                            b1.Property<int>("Rank")
                                .HasColumnType("integer")
                                .HasColumnName("rank");

                            b1.HasKey("GameSessionId", "Id")
                                .HasName("pk_game_session_player_result");

                            b1.HasIndex("MemberId")
                                .HasDatabaseName("ix_game_session_player_result_member_id");

                            b1.ToTable("game_session_player_result", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId")
                                .HasConstraintName("fk_game_session_player_result_game_session_game_session_id");
                        });

                    b.OwnsMany("ChoicePie.Backend.Domain.Aggregates.GameSession.ValueObjects.GameSessionQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("GameSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("game_session_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AnswerIndex")
                                .HasColumnType("integer")
                                .HasColumnName("answer_index");

                            b1.Property<string>("Explanation")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("explanation");

                            b1.PrimitiveCollection<string[]>("Options")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("options");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid")
                                .HasColumnName("question_id");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text");

                            b1.HasKey("GameSessionId", "Id")
                                .HasName("pk_game_session_question");

                            b1.ToTable("game_session_question", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId")
                                .HasConstraintName("fk_game_session_question_game_session_game_session_id");
                        });

                    b.Navigation("PlayerResults");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.Quiz.Quiz", b =>
                {
                    b.OwnsMany("ChoicePie.Backend.Domain.Aggregates.Quiz.Entities.Question", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid?>("CreatorId")
                                .HasColumnType("uuid")
                                .HasColumnName("creator_id");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<Guid?>("DeleterId")
                                .HasColumnType("uuid")
                                .HasColumnName("deleter_id");

                            b1.Property<string>("Explanation")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("explanation");

                            b1.Property<Guid?>("LastModiferId")
                                .HasColumnType("uuid")
                                .HasColumnName("last_modifer_id");

                            b1.Property<DateTime>("LastModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<Guid>("QuizId")
                                .HasColumnType("uuid")
                                .HasColumnName("quiz_id");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text");

                            b1.HasKey("Id");

                            b1.HasIndex("QuizId")
                                .HasDatabaseName("ix_question_quiz_id");

                            b1.ToTable("question", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuizId")
                                .HasConstraintName("fk_question_quiz_quiz_id");

                            b1.OwnsOne("ChoicePie.Backend.Domain.Aggregates.Quiz.ValueObjects.ChoiceSet", "Choices", b2 =>
                                {
                                    b2.Property<Guid>("QuestionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("AnswerIndex")
                                        .HasColumnType("integer")
                                        .HasColumnName("choices_answer_index");

                                    b2.PrimitiveCollection<string[]>("Options")
                                        .IsRequired()
                                        .HasColumnType("text[]")
                                        .HasColumnName("choices_options");

                                    b2.HasKey("QuestionId");

                                    b2.ToTable("question");

                                    b2.WithOwner()
                                        .HasForeignKey("QuestionId")
                                        .HasConstraintName("fk_question_question_id");
                                });

                            b1.Navigation("Choices")
                                .IsRequired();
                        });

                    b.OwnsOne("ChoicePie.Backend.Domain.Aggregates.Quiz.ValueObjects.ChallengeStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("QuizId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("ChallengeCount");

                            b1.Property<decimal>("PassRate")
                                .HasColumnType("numeric")
                                .HasColumnName("PassRate");

                            b1.HasKey("QuizId");

                            b1.ToTable("quiz");

                            b1.WithOwner()
                                .HasForeignKey("QuizId")
                                .HasConstraintName("fk_quiz_quiz_id");
                        });

                    b.OwnsOne("ChoicePie.Backend.Domain.Aggregates.Quiz.ValueObjects.QuizCover", "Cover", b1 =>
                        {
                            b1.Property<Guid>("QuizId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Emoji")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CoverEmoji");

                            b1.Property<string>("Gradient")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CoverGradient");

                            b1.HasKey("QuizId");

                            b1.ToTable("quiz");

                            b1.WithOwner()
                                .HasForeignKey("QuizId")
                                .HasConstraintName("fk_quiz_quiz_id");
                        });

                    b.Navigation("Cover")
                        .IsRequired();

                    b.Navigation("Questions");

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("ChoicePie.Backend.Domain.Aggregates.QuizAttempt.QuizAttempt", b =>
                {
                    b.OwnsMany("ChoicePie.Backend.Domain.Aggregates.QuizAttempt.Entities.QuizAttemptAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AnsweredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("answered_at");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid?>("CreatorId")
                                .HasColumnType("uuid")
                                .HasColumnName("creator_id");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<Guid?>("DeleterId")
                                .HasColumnType("uuid")
                                .HasColumnName("deleter_id");

                            b1.Property<Guid?>("LastModiferId")
                                .HasColumnType("uuid")
                                .HasColumnName("last_modifer_id");

                            b1.Property<DateTime>("LastModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid")
                                .HasColumnName("question_id");

                            b1.Property<Guid>("QuizAttemptId")
                                .HasColumnType("uuid")
                                .HasColumnName("quiz_attempt_id");

                            b1.Property<int>("SelectedOptionIndex")
                                .HasColumnType("integer")
                                .HasColumnName("selected_option_index");

                            b1.HasKey("Id");

                            b1.HasIndex("QuizAttemptId")
                                .HasDatabaseName("ix_quiz_attempt_answer_quiz_attempt_id");

                            b1.ToTable("quiz_attempt_answer", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuizAttemptId")
                                .HasConstraintName("fk_quiz_attempt_answer_quiz_attempt_quiz_attempt_id");
                        });

                    b.OwnsOne("ChoicePie.Backend.Domain.Aggregates.QuizAttempt.ValueObjects.AttemptScore", "Result", b1 =>
                        {
                            b1.Property<Guid>("QuizAttemptId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Score");

                            b1.HasKey("QuizAttemptId");

                            b1.ToTable("quiz_attempt");

                            b1.WithOwner()
                                .HasForeignKey("QuizAttemptId")
                                .HasConstraintName("fk_quiz_attempt_quiz_attempt_id");
                        });

                    b.Navigation("Answers");

                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
